export const ELEMENTS = {
    classeItemLista: '.inventory_item_name',
    listaTxtItem1:'Sauce Labs Backpack',
    listaTxtItem2:'Sauce Labs Bike Light',
    listaTxtItem3:'Sauce Labs Bolt T-Shirt',
    listaTxtItem4:'Sauce Labs Fleece Jacket',
    listaTxtItem5:'Sauce Labs Onesie',
    listaTxtItem6:'Test.allTheThings() T-Shirt (Red)',
    produto1:'#item_1_title_link',
    produto2:'#item_4_title_link',
    produto3:'#item_3_title_link',
    classeItemCarrinho:'.inventory_item',
    btnAdicionaraoCarrinho: '.btn_primary.btn_inventory',
    quantidaDeItem: '.shopping_cart_badge',
    btnPaginaDeCarrinho2:'.shopping_cart_link',
    classeRemoveItem: '.cart_item',
    btnRemoverItem:'.btn_secondary.cart_button',
    btnProximapagina:'a[class="btn_action checkout_button"]',
    link: '/cart.html'
   }